### PR TITLE
Added Xcode 8 (Beta 6) support

### PR DESCRIPTION
**Pull request by mohpor**
Hi,

I have added Swift 3 support.

Sincerely,
M.

### CODE REVIEW

**Comment by mohpor** [comment]
This is still a work in progress.

**Comment by mohpor** [comment]
@dev-aleksey,
I have a problem:
It seems like `alphaAnimation` doesn't work anymore! I have tested many combinations, but I'm getting weird results animating `blurView`. it fades with a white layer and then jumps right to the conclusion.

When I investigated more, I have found that the effect view consists of two different views, one is a backdrop which is the blur effect, the other one plays the role of a tint layer which adds/subtracts hue/brightness for different blur effect settings (light, extra light, dark). but, right to the end of the animation (or when the opacity of `blurView`s layer opacity reaches 1) the effect backdrop is just a snapshot of the containing view, with no blur effect on it.
I'm guessing this is a Beta Bug and I hope it gets fixed soon.

**Comment by mohpor** [comment]
@dev-aleksey 

The animation has been fixed for the blur view.

After much investigation, I have found that the problem is related to the effect view not being able to correctly render it's backdrop due to size and opacity change. I have changed the dynamics of the animation and used a snapshot for the blur view's backdrop, it has a better performance and a more robust animation.

It'd be nice to see this PR merged.

Sincerely,
M.

P.S.: I have a project which has been under development for a long time now. As Xcode 8 release getting imminent, I have decided to update all the frameworks which my projects is depending on to support the migration. This library is on my list.

**Comment by 0ber** [comment]
thanks

**Pull request merged**
